version: 1
formatters: 
  standard: 
    class: logging.Formatter
    format: "%(asctime)s | %(levelname)s | %(message)s"
    datefmt: "%Y/%m/%d %H:%M:%S"
handlers:
  console:
    class : logging.StreamHandler
    formatter: standard
    level   : INFO
    stream  : ext://sys.stdout
  # file:
  #   class : logging.handlers.RotatingFileHandler
  #   level : WARNING
  #   formatter: standard
  #   filename: tmp/log/error.log
root: 
  level: INFO
  handlers:
    - console
    # - file
